import { BsGithub } from 'react-icons/bs'
type Project = { name: string; status: 'Completed' | 'In Progress'; tag: string; tech: string; description: string; link: string }
const projects: Project[] = [
  { name: 'ChemLabWizard', status: 'Completed', tag: 'FOSSEE Internship', tech: 'Django · React · PyQt5', description: 'A chemistry lab simulation tool built during the FOSSEE internship, combining a Django/React web frontend with a PyQt5 desktop component.', link: 'https://github.com/smitpatil06' },
  { name: 'Sim Runner', status: 'Completed', tag: 'FOSSEE Internship', tech: 'Simulation Engine', description: 'The latest build from the FOSSEE internship — a runner for executing and managing simulation workflows.', link: 'https://github.com/smitpatil06/Sim-Runner' },
  { name: 'CF26-S03 — Infrastructure Cascade Simulator', status: 'Completed', tag: 'Hackathon', tech: 'Discrete-Time Simulation', description: 'Built for a hackathon problem statement: a discrete-time simulation engine that models cascading failure across interdependent urban networks — power, healthcare, transport, and communication.', link: 'https://github.com/smitpatil06/CF26-S03-Smasherz' },
  { name: 'Cogni', status: 'Completed', tag: 'WeMakeDevs x Cognee Hackathon · Team of 4', tech: 'Postgres · Multi-Agent Systems · GitHub API', description: 'A real-time collaborative coding platform. Built the agent layer using branch-based memory graphs across five agents (Base, Coding, Context, Memify, Merge), plus a Postgres-backed memory merge module and frontend integration.', link: 'https://github.com/smitpatil06' },
  { name: 'RAG System from Scratch', status: 'Completed', tag: 'Learning Project', tech: 'Gemini Embeddings · Groq API · Python', description: 'A deliberately basic retrieval-augmented generation pipeline built to understand the concepts: extracts text from a PDF, chunks it, creates embeddings, and does cosine-similarity search without a vector database — plus a ReAct-style tool-calling agent on Groq (llama-3.3-70b-versatile).', link: 'https://github.com/smitpatil06' },
  { name: 'Web Inspectora', status: 'Completed', tag: 'Personal Project', tech: 'Web Auditing', description: 'A tool for inspecting and auditing websites.', link: 'https://github.com/smitpatil06/Web_Inspectra' },
  { name: 'Micro-SME AI Invoice Manager', status: 'In Progress', tag: 'Personal Project', tech: 'Django REST Framework · Next.js · PostgreSQL · Docker', description: 'A full-stack invoice management system with an LLM-based extraction layer for automated invoice parsing. Backend scaffolding, data models, serializers, and JWT auth are done, running on a production-grade Docker Compose setup.', link: 'https://github.com/smitpatil06' },
  { name: 'AutoBill Agent', status: 'In Progress', tag: 'Qwen Cloud Hackathon', tech: 'LangGraph', description: 'An agentic billing assistant built with LangGraph for the Qwen Cloud Hackathon. Still under active development.', link: 'https://github.com/smitpatil06' },
  { name: 'Neural Networks from Scratch', status: 'Completed', tag: 'Learning Project', tech: 'Python', description: 'A custom autograd engine and a bigram language model built from first principles to understand backpropagation and neural network training.', link: 'https://github.com/smitpatil06/Neural-Networks' },
  { name: 'PUCH AI Hackathon — MCP Server', status: 'Completed', tag: 'Hackathon', tech: 'FastAPI · Python · MCP', description: 'An MCP server built with FastAPI, featuring a resume analyzer and a basic emotion-based music recommendation tool.', link: 'https://github.com/mayu2989/puch-7B07951D' },
]
export default function Projects() { return <section id="projects" className="section section-quiet"><div className="page-width"><h2>Projects</h2><p className="section-intro">A mix of hackathon builds, internship work, and first-principles learning projects.</p><div className="project-list">{projects.map((project) => <a key={project.name} href={project.link} target="_blank" rel="noopener noreferrer" className="project"><div><div className="project-heading"><h3>{project.name}</h3><span>{project.status}</span></div><p className="accent-copy">{project.tag}</p><p className="project-tech">{project.tech}</p><p>{project.description}</p></div><div className="repo-link"><BsGithub /> <span>View repository</span></div></a>)}</div></div></section> }
